[workspace]
members = [
    "embers",
    "embers-macros",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["TransparentWhite", "tlqqhfhc"]
edition = "2024"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
strip = "debuginfo"

[workspace.dependencies]
avian3d = "0.6"
bevy = { version = "0.18", features = [] }
bevy_hanabi = "0.18"
bevy-tnua = "0.31"
bevy-tnua-avian3d = "0.11"
bevy_voxel_world = "0.16"
image = { version = "0.25", default-features = false }
winit = { version = "0.30", default-features = false }
atomicow = "1.2"
anyhow = "1.0"
delegate = "0.13"
derive-where = "1.6"
duplicate = "2.0"
rand = "0.10"
regex = "1.12"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
toml = "1.1"
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

[workspace.lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
