name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Format
        run: cargo fmt --verbose --all --check
  lint_test_build:
    name: Lint, Test, and Build
    needs: format
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        toolchain:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Setup
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Setup [Linux]
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwayland-dev libasound2-dev libudev-dev lld
      - name: Setup [Windows]
        if: runner.os == 'Windows'
        run: |
          cargo install -f cargo-binutils
          rustup component add llvm-tools-preview
      - name: Lint
        run: cargo clippy --verbose --workspace --all-targets --features dev
      - name: Test
        run: cargo test --no-fail-fast --verbose --workspace --all-targets --features dev
      - name: Lint [Release]
        run: cargo clippy --verbose --workspace --all-targets --all-features --release
      - name: Build [Release]
        run: cargo build --verbose --release
      - name: Extract
        shell: bash
        run: |
          mkdir -p dist
          if [ "${{ runner.os }}" == "Windows" ]; then EXT=".exe"; fi
          cp "target/release/embers$EXT" "dist/embers-${{ runner.arch }}-${{ runner.os }}$EXT"
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: embers-${{ runner.arch }}-${{ runner.os }}
          compression-level: 9
          path: dist/embers-*
